
version: '3'


services:
    course-catalog:    
        build: 
            context: ./course_catalog
            dockerfile: Dockerfile
        container_name: course-catalog
        ports:
          - 8761:8761 # Forward the exposed port 8761 on the container to port 8761 on the host machine
    course-registration:    
        build: 
            context: ./course_registration
            dockerfile: Dockerfile
        container_name: course-registration     
        depends_on:
          - course-catalog
    student-details:
        build:
            context: ./student_details
            dockerfile: Dockerfile
        container_name: student-details
        depends_on:
          - course-catalog 

 