spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: student-service
                fallbackuri: forward:/studentFallBack
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
          filters:
            - name: CircuitBreaker
              args:
                name: course-service
                fallbackuri: forward:/courseFallback


server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000